name: docs2native
description: Convert docs into a desktop app
author: DrSensor
branding:
  icon: book-open
  color: white

inputs:
  generator:
    description: Static site generator to be used
    required: true
  docs:
    description: Docs path or repository
    required: true
outputs:
  path:
    description: Path to executable file
  name:
    description: Generator name

runs:
  using: node12
  main: dist/index.js
