name: docs2native
description: Convert docs into a desktop app
author: DrSensor
branding:
  icon: book-open
  color: white

inputs:
  generator:
    description: Static site generator to be used
    default: auto
  command:
    description: Command for generating static site
    required: false
  docs:
    description: Docs path or repository
    required: true
outputs:
  path: Path to executable file 

runs:
  using: node12
  main: dist/index.js
