name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |-
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Test this action
      uses: ./
      with:
        docs: ./docs
        generator: hugo
      id: docs
    - uses: actions/upload-artifact@v1
      with:
        name: hugo-${{ matrix.os }}
        path: ${{ steps.docs.outputs.path }}
