name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - feature/tauri
      - 'releases/*'

jobs:
  # unit-test: # make sure build/ci work properly
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: scripts/prepare-docs.sh ${{ matrix.generator }}
  #   - run: npm install
  #   - run: npm run all
  smoke-test: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare docs
      shell: bash
      run: |-
        git clone --depth 1 https://github.com/gohugoio/hugoBasicExample.git   docs/hugo
        git clone --depth 1 https://github.com/budparr/gohugo-theme-ananke.git docs/hugo/themes/ananke
        echo 'theme = "ananke"' | cat - docs/hugo/config.toml > docs/config.toml
        mv docs/config.toml docs/hugo/config.toml
    - name: Test this action
      uses: ./
      with:
        docs: ./docs/hugo
        generator: hugo
      id: docs
    - uses: actions/upload-artifact@v1
      with:
        name: hugo-${{ matrix.os }}
        path: ${{ steps.docs.outputs.path }}
